nix-community/nixos-generators

README.md, bin/make-iso, bin/make-openstack, bin/make-virtualbox, bin/run-vm
```
./bin/make-iso 
```
is the same like 
```
./bin/make-iso config.nix
```
now
=> config.nix is an optional argument now

formats/qcow.nix, formats/raw.nix
=> Set filesystem

README.md
Also use SPDX full name
https://spdx.org/licenses/MIT.html
=> Add link to LICENSE file to README

README.md, formats/do.nix
A module for Digital Ocean was recently merged in nixpkgs: https://github.com/NixOS/nixpkgs/pull/66978. This PR adds a corresponding format.
=> Add a Digital Ocean format.

.gitlab-ci.yml, .included.yml, README.md, formats/install-iso-hyperv.nix, nixos-generate
missed gitlab ci support for the nixos generators project.
added as many formats as possible.
running example:
https://gitlab.com/MaCXyLo/nixos-generators/pipelines/99808542
=> add support for gitlab ci

nixos-generate
This flag is available on all nix-related commands. Migth as well have
it too!
=> nixos-generators: add --show-trace option

formats/hyperv.nix, formats/install-iso-hyperv.nix, formats/install-iso.nix, formats/iso.nix, formats/kexec.nix, formats/lxc-metadata.nix, formats/lxc.nix, formats/raw.nix, formats/virtualbox.nix, nixos-generate, nixos-generate.nix
This adds an option to specify the path to the generated file in the output directory. currently if there are multiple files In the generated directory we get the first one and hope it's the right one. With hyper-v this doesn't seem to work correctly. So I though up this solution.
option-name is up for debate. It was just the first thing that came to mind.
EDIT: should be ready now
=> add filename option

nixos-generate
Allows the user to specify a custom `--out-link` for nix-build
=> feat: add outlink option

README.md, formats/vm-bootloader.nix
=> feat: add vm-bootloader target referencing vmWithBootLoader

nixos-generate
See https://github.com/nix-community/nixos-generators/pull/76#issuecomment-805667199
=> flake info subcommand was renamed to metadata

formats/lxc.nix
I am very new to NixOS and there's not much information I can find on making LXC images, but with a bit of experimentation I found this creates LXC images successfully.
Closes #92
=> Fix copying of LXC system contents

README.md, formats/proxmox.nix
https://github.com/NixOS/nixpkgs/pull/144013
=> add proxmox (vma) image format

README.md, flake.nix
Feeling a little out of my depth, but an attempt to address #94, which is similar to some use cases I have.  An example of how I'd like to use this [here](https://github.com/mayl/generatorFlakes). 
Several things about this implementation seem really hacky, particularly using a `callPackage` call purely to extract the `formatAttr` value out of a format file.  Review, comments and suggestions of other approaches are much appreciated!
=> adds nixosGenerate function

README.md
Flakes profile installation method
=> Mention flake profile

README.md, formats/kubevirt.nix
requires https://github.com/NixOS/nixpkgs/pull/151482
Signed-off-by: jbpratt <jbpratt78@gmail.com>
=> implement kubevirt format

README.md, formats/proxmox-lxc.nix
https://github.com/NixOS/nixpkgs/pull/160195
=> add proxmox LXC format

formats/raw-efi.nix, formats/vm-nogui.nix
some minor fixes for raw-efi-boot and vm-nogui
=> raw-efi-boot fixes

README.md
Added configuration examples and references, updated `binfmt` nix options.
Also fixed some typos and small edits. :D
=> README.md: update cross compiling section

formats/docker.nix, formats/kexec.nix, formats/lxc-metadata.nix, formats/lxc.nix, formats/proxmox-lxc.nix
=> for containers & kexec, `boot.loader.*.enable = lib.mkForce false;`

nixos-generate
Just a simple wrapper for convenience
=> feat: add `--special-arg` option

formats/vm.nix
=> Set nixos diskSize option only if specialArgs.diskSize exists

default.nix, package.nix
fixes https://github.com/nix-community/nixos-generators/issues/356
=> package.nix: add missing gnuawk

all-formats.nix, formats/sd-aarch64-installer.nix, formats/sd-aarch64.nix, formats/sd-x86_64.nix
- **formats: init sd-x86_64**
- **all-formats: several improvements**
=> improve all-formats and sd image outputs

README.md, formats/cloudstack.nix
Title says it all. Opted for `ext4` as a conservative choice.
=> Fix cloudstack eval, mention sd-x86_64 in README

README.md, all-formats.nix, configuration.nix, flake.lock, flake.nix, format-module.nix, formats/cloudstack.nix, formats/hyperv.nix, formats/kexec.nix, formats/proxmox-lxc.nix, formats/proxmox.nix, formats/qcow-efi.nix, formats/qcow.nix, formats/raw-efi.nix, formats/raw.nix, formats/vm.nix, formats/vmware.nix, nixos-generate.nix
This depends on nixpkgs PR https://github.com/NixOS/nixpkgs/pull/339535, so I am drafting it here for visibility, feedback and CI :)
=> Use virtualisation.diskSize instead of specialArg
