nix-community/nixos-generators

README.md, bin/make-kexec-bundle, lib/kexec.nix
Now you can build dangerous system-converting executables. Be very careful not to run this on any established systems.
I've used this many times with my own systems, but not yet in this combination.
=> add make-kexec-bundle

nixos-generate
This could be useful if the machine has remote builders setup that
support the target system.
=> add option to specify the target system

README.md, formats/sd-aarch64-installer.nix, formats/sd-aarch64.nix
This additional format expression enables for baking a non-installer system config directly into the resulting image file.
In order to do this i basically copied the initial expression from <nixpkgs> and ripped out any installer related things.
=> Add format sd-aarch64-noinstaller

configuration.nix
Now it not only builds but is also usable.
- You can login as root with password "nixos"
- You are logged in automatically on console (like installer)
- You can login as root with SSH
- You can connect to port 80
I have tested it with format "virtualbox" and "install-iso".
It's not best practice to use such insecure password,
but it's probably OK for this example for people to
see that it works.
=> Extend default/example config to actually work

nixos-generate
We should ignore the nix-support directory. This should fix https://github.com/nix-community/nixos-generators/issues/39
=> ignore nix-support directory when finding filename

formats/sd-aarch64.nix
Here is the related upstream changes that break the current format
https://github.com/NixOS/nixpkgs-channels/blob/nixos-19.09/nixos/modules/installer/cd-dvd/sd-image.nix#L83-L100
=> sd-aarch64 format, sdImage module has been refactored with new attributes

formats/lxc.nix
It's not needed for all lxc images, and for those where it is
it can be easily added to the configuration.nix for that image.
This makes for a smaller image, as gcc alone is 140M.
=> Don't necessarily include pkgs.stdenv in lxc image

README.md
Using `qcow2` as the the current documentation mentions gives:
```
error: file 'format-config' was not found in the Nix search path
```
Using `qcow` works as expected.
=> Qcow docfix

README.md, formats/hyperv.nix
Follow up to https://github.com/NixOS/nixpkgs/pull/83930
This allows us to create VHDX files for Hyper-V.
Note: The file that is output at the end of this generation is an `img` file.
e.g.
```
[    1.440485] reboot: Power down
/nix/store/bx4132wc00d8dg10krslzh27bjm93sf7-nixos-hyperv-20.09pre226148.0f5ce2fac0c-x86_64-linux/nixos.img
```
~~The VHDX file _is_ located alongside the `img` file, but my guess is that we don't need the `img` file, and that the VHDX file should be printed in its place upon generation.~~
~~Not sure how I should handle this/if there's a format that does anything similar.~~
I updated `hyperv-image.nix` to remove `$baseImage` after the VHDX is created, like the azure image does here:
https://github.com/NixOS/nixpkgs/blob/4a302d1b9aab8c767bdae26a1d5bcc5dbdcb796a/nixos/m …
=> Add Hyper-V format

README.md, formats/vmware.nix
This enables `nixos-generate` to create VMDK images for VMWare hypervisors.
This depends on https://github.com/NixOS/nixpkgs/pull/88474.
=> Add VMWare format

formats/raw-efi.nix, formats/raw.nix
- Added the kernel module `uas` which allows to boot the raw formats from a usb stick.
- Replaced the use of `mkForce` in `raw-efi.nix` with `mkOverride 999` , since `mkForce` might have the unwanted side effect to overwrite ones settings from the configuration.nix.
=> add usb kernel module to raw formats; remove use of mkForce

README.md, formats/vagrant-virtualbox.nix
This will ultimately replace the nix-community/nixbox project.
Change the configuration.nix to not include the installation ISO to
something like this:
```nix
{ config, lib, pkgs, modulesPath, ... }:
{
documentation.man.enable = false;
documentation.nixos.enable = false;
sound.enable = false;
}
```
See https://github.com/nix-community/nixbox/issues/38
Depends on https://github.com/NixOS/nixpkgs/pull/76071
=> new format: vagrant-virtualbox

.envrc, flake.lock, flake.nix, nixos-generate, nixos-generate.nix, shell.nix
**NOTE: I have not tested this on a non-flake system. Kinda just hoping there's a CI that tests this :stuck_out_tongue:** 
I did test it with `nix-shell -p nix`, and that seems to work lovely, which is weird.
You currently have to mark all your nixosSystems with `lib.makeOverridable`. I might send a PR to nixpkgs that runs this by default.
Test it using flakes:
```sh
nix run github:jD91mZM2/nixos-generators/flake -- --help
```
=> Flake support

formats/raw-efi.nix, formats/raw.nix
As a follow up to #56 and the fix made because of it https://github.com/NixOS/nixpkgs/pull/89331, remove the 2GB size limit on raw disks.
=> allow raw disk size to automatically increment

flake.nix, format-module.nix, nixos-generate.nix
This project has some really cool modules that I want to make use of. I'd like to do it properly by getting them exported in this flake under `nixosModules`.
=> flake: export formats as nixosModules

formats/kexec.nix
The old version expected a hardcoded `bzImage` kernel image, but AArch64 uses an uncompressed `Image`. This was fixed in https://github.com/cleverca22/nix-tests/commit/a9a316ad89bfd791df4953c1a8b4e8ed77995a18, so this PR updates to that commit.
=> Update `cleverca22/nix-tests` to fix kexec on AArch64

flake.lock, flake.nix
This seems odd, but it works since input dependencies are lazily fetched
that means a downstream repo, that only consumes the modules output
(like for example `divnix/digga`), does never fetch nor instantiate
nixpkgs proper (which would be costly).
This enables `divnix/digga` to continue to _not_ depend on `nixpkgs`
for operation.
(it still depends on `nixpkgs` as a strict development dependency, but
beacause of the black magic which I describe above, no end user
will ever fetch it's depenency on `nixpkgs`.)
So, here, we implement a similar trick to avoid acquiring deps
where they should _not_ be acquired.
=> For module-only consumers, avoid depending on nixpkgs

configuration.nix
Hello,
I just tried to run `nixos-generate -f lxc' and ran into the following error
```
trace: warning: The option `services.mingetty' defined in `/nix/store/msm51p54fsvnq1h593blkrdffxc3axxx-nixos-generators-1.3.0/share/nixos-generator/configuration.nix' has been renamed to `services.getty'.
```
This was changed in January: see NixOS/nixpkgs#108465
Patching with `substituteInPlace` in `postPatch` fixed this, so I'm pushing the fix upstream. TIL what `getty` is 🚀 .
I've tested the patched nixos-generators using `lxc image import $(nixos-generate -f lxc-metadata) $(nixos-generate -f lxc) --alias nixos` and the resulting container runs fine on chromeos.
=> Replace deprecated mingetty option with getty

flake.lock
Hi,
I tried to install nixos-generators using `nix profile install github:nix-community/nixos-generators` and ran into this error
```
cannot write modified lock file of flake 'github:nix-community/nixos-generators' (use '--no-write-lock-file' to ignore)
```
I updated the flake.lock. This was probably forgotten after changing the flake input from `divnix/nixpkgs.lib` to `nix-community/nixpkgs.lib`.
=> Update flake.lock 

formats/lxc-metadata.nix, formats/lxc.nix
This replaces the current implementation and directly uses the one from nixpkgs, as is availabie in unstable
Since 21.11 is basically around the corner deperacting 21.05 there shouldn't be too much concern for backwards compatibility
=> lxc: use new build system from nixpkgs directly

formats/qcow.nix
Thoughts? qcow is most likely to be used in a hypervisors and most hypervisors use virtio.
=> qcow: also add kernel drivers

nixos-generate.nix
I think this is a much cleaner solution. It does require nixosSystems built with a version of the module system past this commit: https://github.com/NixOS/nixpkgs/pull/143207. I think thats still much better than requiring `makeOverridable`. 
fixes #110
=> nixos-generate: use extendModules for flakes

formats/kexec.nix
should fix https://github.com/nix-community/nixos-generators/issues/142
=> kexec-bundle: get kexec_tarball from module system

README.md
document some of the common errors which hide behind `No space left on device` which were encountered in https://github.com/nix-community/nixos-generators/issues/73
=> README: add FAQ section

flake.nix
This allows passing flake inputs to the underlying configuration ala https://nixos.wiki/wiki/Flakes#Using_nix_flakes_with_NixOS
I'm new to nix so apologies if this isn't the right way to do this.
=> pass specialArgs through to nixosSystem

.included.yml, nixos-generate
Some formats (e.g. `vm` and `vm-nogui`) have `config.filename` values that refer to symlinks to regular files rather than regular files, full stop.  This changeset updates the `find` invocation near the end of `nixos-generate` to use `-xtype f` rather than `-type f`, thus catching regular files **and** symlinks to regular files.
Additionally, this changeset updates the GitLab CI configuration to assert that the final line of output from `nixos-generate -f <format> [<args>]` refers to a Nix store path that is a regular file or symlink thereto.
Thank you!
=> Handle "config.filename" output path that is a symlink to a regular file

nixos-generate
Just a small change to fix the description of the "-o" option.
=> docs: fix description for `-o`

formats/kexec-bundle.nix
Cherry-picked from #155.
This PR adds an explicit `filename` attribute definition to [the `kexec-bundle` format](./formats/kexec-bundle.nix), as the `filename` definition "inherited" from [the `kexec` format](./formats/kexec.nix) is not appropriate (does not match any output paths of `kexec-bundle`).
=> kexec-bundle: define filename pattern

README.md, formats/linode.nix
Builds `result/nixos.img.gz` image which can be uploaded and run
directly on Linode without an installation process.
Known working settings when setting up Linode:
Configure two disks:
- Label: /dev/sda   Filesystem: ext4 (from uploaded .img.gz image)
- Label: /dev/sdb   Filesystem: swap
Create configuration:
- VM Mode: Paravirtualization
- Kernel: GRUB 2
- Run Level: Run Default Level
- Memory Limit: Do not set any limits on memory usage
- Block Device Assignment:
- - /dev/sda -> /dev/sda
- - /dev/sdb -> /dev/sdb
- Use custom root: No
- Root device: /dev/sda
- Enable distro helper: No
- Disable updatedb: No
- Enable modules.dep helper: No
- Auto-mount devtmpfs: No
- Auto-configure networking: No
Using information from:
- https://www.linode.com/docs/guides/install-nixos-on-linode/
- …
=> formats/linode: Add support for generating linode images

README.md, flake.nix
Fixes https://github.com/nix-community/nixos-generators/issues/172
Updating the flake in that issue to follow the new guidance causes both packages in the flake to build successfully.
=> nixosGenerate: allow and suggest leaving pkgs set to null

flake.nix
`nixosSystem` does enable to set `lib` which by default uses the [`$NIXPKGS/lib`](https://github.com/NixOS/nixpkgs/tree/7fad01d9d5a3f82081c00fb57918d64145dc904c/lib). I'm using `lib` to extend the standard library with my own functions. While importing the custom functions inside of the NixOS module is always an option, I do use it throughout all of the modules so it will be tedious if I go with that route. So instead, I'm adding the option to do so in `nixosGenerate`.
I tried to make as minimal disruptions as possible with this change. This should successfully build the images without much changes. I also tested the examples (e.g., `vmware` and `vbox` image from the README) and my own images (with the custom `lib`) and both cases successfully built.
The biggest caveat so far is using …
=> nixosGenerate: add lib parameter

formats/raw-efi.nix, formats/raw.nix
Locating the ESP via /dev/vda1 fails when booting on hardware.
Also, make the grub timeout configurable on raw + raw-efi.
=> raw-efi: Locate ESP by disk label instead of /dev/vda1

README.md
Documenting some tweaks I found helpful when trying to figure out why my `raw-efi` image was failing to boot on hardware. The defaults make investigating problems a bit difficult, so I think it'd be useful to document these workarounds in the readme.
(I separated this from #198 since that change on its own is a straightforward bugfix.)
=> Add some notes to README.md about raw & raw-efi images on hardware.

flake.lock
This commit updates the flake inputs of nixos-generators, as they are currently very outdated, which can cause a range of issues for users of nixos-generators who does not override these inputs to newer versions themselves.
The change was tested by running `nix flake show` to verify that the nixosModules outputs are generated correctly with the new version of `nixpkgs.lib`.
=> lockfile: Update inputs

flake.nix
not consistent with:
```
inputs = {
nixpkgs.url = "nixpkgs/nixos-unstable";
nixos-generators = {
url = "github:nix-community/nixos-generators";
inputs.nixpkgs.follows = "nixpkgs";
};
};
```
=> fix deprecation message

README.md, all-formats.nix, checks/test-all-formats-flake/flake.nix, checks/test-all-formats.nix, checks/test-customize-format.nix, flake.nix
While the `all-formats.nix` module (introduced via https://github.com/nix-community/nixos-generators/pull/241) allows to import all formats at once, it lacks an interface to customize formats or add formats.
This is fixed by adding the top-level option `formatConfigs` (attrsOf deferredModule).
All format modules created under `config.formatConfigs` are mapped so their outputs are available under `config.formats` which has also been moved to the top-level (previously `config.system.formats`).
Done:
- expose the `all-formats` module via `nixosModules`
- add option `formatConfigs` (pre-populated with all existing formats)
- move option `system.formats` -> `formats`
- add test for customizing a format
- add example to readme
- add test similar to the new readme example ensuring that formats …
=> improve all-formats module: support customizing and creating formats + add tests + add readme

configuration.nix, flake.nix
Since we generate whole images we don't have state and can always go with the last.
=> configuration: get rid of warnings

formats/linode.nix
Very simple fix but enables users to nixos-rebuild switch without failure to find said coreutil.
=> fix: extra install commands require full pathing on linode.nix script

formats/azure.nix
Been banging my head against a wall for multiple days now trying to debug my [nixos-image](https://github.com/physics-enthusiast/nixos-image) azure builds, which were failing at random for what seemed to be no discernable cause, and I think I finally figured it out. From what I can tell, a file extension must specified in the format definition unless the format derivation produces only one file so that the [find query](https://github.com/nix-community/nixos-generators/blob/13ff43edfb6c2fc0ccb26f4c31a573ff45f02953/all-formats.nix#L36) and subsequent symlink works properly. Due to the presence of what appears to be [hydra metadata](https://github.com/NixOS/nixpkgs/blob/804761c3110e46c209c49fee5cc7addf8b4c62cc/nixos/lib/make-disk-image.nix#L527) created by make-disk-image in $out, there is …
=> Fix failing azure builds

README.md, formats/hyperv.nix, formats/proxmox.nix, formats/qcow.nix, formats/raw-efi.nix, formats/raw.nix, formats/vm.nix, formats/vmware.nix, nixos-generate, nixos-generate.nix
Many formats generate an image only large enough for the generated NixOS config. This quickly runs out of space for NixOS servers that are updated over time rather than being redeployed with fresh images.
---
I am still learning Nix and NixOS and am open to feedback on how to improve the PR.
=> Add disk-size argument

flake.nix
It is expected to be a Nix module where this could be a path, function, or an attribute set.
=> nixosGenerate: fix extraFormats value

README.md
=> fix: typo, function is called `nixosGenerate` not `nixos-generate`

nixos-generate
nix-build doesn't print any logs when performs derivation looks up, which might look like the build stalled.
=> nixos-generate: switch to new nix build command for better logs

nixos-generate
The error:
```
$ nixos-generate --help
/nix/store/...-nixos-generate/bin/.nixos-generate-wrapped: line 25: specialArgs: command not found
Usage: /nix/store/...-nixos-generate/bin/.nixos-generate-wrapped [options]
...
=> nixos-generate: fix "specialArgs: command not found"

formats/install-iso.nix, formats/iso.nix
For most users of nixos-generate zstd will be the better choice as it will build and boot images much faster. Often users have to rebuild images a couple of times before they are happy with the result. NixOS might be better of with xz as it saves download and storage cost for images.
=> iso: default to zstd compression

README.md
Previously, it did not compile.  The goal of the section appears to have been to describe how to make a nixosModule that will imbue format magic upon configurations referencing it.  With that in mind, I also changed comments and attribute names to make it more clear that the nixosConfiguration is using the nixosModule rather than integral to it or vice versa.
=> Fix nixosModules example

formats/docker.nix, formats/install-iso-hyperv.nix, formats/install-iso.nix, formats/iso.nix, formats/linode.nix, formats/openstack.nix
Note: This is based on https://github.com/nix-community/nixos-generators/pull/375, so please begin your review at 1dee94896d61bc31c71bc832523306efd6db5d50 or wait for a merge of the former PR and the following rebase :)
Started to go through the modules and compare them to upstream nixpkgs in order to reuse new upstream modules (linode) and remove attributes which are nowadays a default with the same priority in upstream nixpkgs.
=> Cleanup, De-duplicate with upstream nixpkgs

nixos-generate
FIXES: https://github.com/nix-community/nixos-generators/issues/422
When using `--argstr` to pass the `--disk-size` argument through to the `virtualisation.diskSize` option, Nix will always complain that it has been provided a string when it needs an int or the string `auto`.
This fixes for that by using `--arg` to pass the value through to `nix build` for the `virtualisation.diskSize` option instead of `--argstr`, and then wrapping any **non-integer** arg in quotes (where integer is assumed by testing whether the arg contains only numerals) so that non-integer args are evaluated as strings by Nix.
NOTE:
Passing it through with quote-wrapping for strings, rather than throwing an error inside `nixos-generate`, allows for Nixpkgs to check and provide its own errors, as well as hopefully …
=> fix: Make sure the "--disk-size" arg is correctly interpreted as an int by Nix, when an int is provided

nixos-generate
Previously, options would only be passed to `nix-build`.
Closes #425
=> fix: Pass `--option` to all nix-* commands
